### ISSUE TITLE
Error building `javax.mail`on ppc64le platform

### ISSUE THREAD

**Issue by sarveshtamba** [jakartaee/mail-api#443] opened 2020-04-17 06:50 UTC
Trying to build `javax.mail` v1.5.6 and v1.6.2 (REPOSITORY="https://github.com/javaee/javamail.git") on ppc64le platform, however facing the following errors:-
```
[ERROR] /root/jasypt/jasypt-1.9.3/jasypt/src/test/java/org/jasypt/normalization/NormalizationTest.java:[41,129] unmappable character for encoding US-ASCII

Tests in error:
  testEncryptAndDecrypt(org.jasypt.encryption.pbe.PBEWithSHA1AndRC2_40StringEncryptorTest): java.security.NoSuchAlgorithmException: PBEWithSHA1AndRC2_40 SecretKeyFactory not available
  testEncryptAndDecrypt(org.jasypt.encryption.pbe.PBEWithSHA1AndRC2_40ByteEncryptorTest): java.security.NoSuchAlgorithmException: PBEWithSHA1AndRC2_40 SecretKeyFactory not available
  testEncryptAndDecrypt(org.jasypt.encryption.pbe.PBEWithSHA1AndRC2_40BigDecimalEncryptorTest): java.security.NoSuchAlgorithmException: PBEWithSHA1AndRC2_40 SecretKeyFactory not available
  testEncryptAndDecrypt(org.jasypt.encryption.pbe.PBEWithSHA1AndRC2_40BigIntegerEncryptorTest): java.security.NoSuchAlgorithmException: PBEWithSHA1AndRC2_40 SecretKeyFactory not available

Failed tests:
  testSSL(com.sun.mail.util.WriteTimeoutSocketTest)
  testSSLSocketFactory(com.sun.mail.util.WriteTimeoutSocketTest)

Running com.sun.mail.util.WriteTimeoutSocketTest
javax.mail.MessagingException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
javax.mail.MessagingException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
```
Any inputs will be highly appreciated.

**Comment by sarveshtamba** [comment] 2020-04-21 10:04
@bshannon any inputs on this one?

**Comment by bshannon** [comment] 2020-04-21 20:33
If all the errors are crypto errors, then it looks like all the crypto providers aren't available
on this platform.  That's not really a Mail issue.  You might need help from a JDK crypto
expert.

**Comment by jmehrens** [comment] 2024-02-20 06:24
Duplicate of: https://github.com/jakartaee/mail-api/issues/375

**Closed by jmehrens** 2024-02-20 06:24 UTC
